Implemented proof-of-concept for #29023.
This commit implements the idea I described in this comment:

https://code.djangoproject.com/ticket/29023#comment:5

Namely, when running tests in parallel, if a test exception occurs
and the exception is either (1) chained, or (2) not picklable, the
test runner will render the exception information to a string and
wrap the string in a `ParallelTestException`. This makes the full
exception information picklable and displayed by the test runner.
In addition, in the case of (2), the pickling exception is also
included in the information.

For example, this is what a chained exception looks like without
the patch:

    ======================================================================
    ERROR: test_chain (paralleltest.tests.test_chain.ChainTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/.../python3.6/unittest/case.py", line 59, in testPartExecutor
        yield
      File "/.../python3.6/unittest/case.py", line 605, in run
        testMethod()
      File "/.../paralleltest/tests/test_chain.py", line 13, in test_chain
        raise KeyError('bar')
    KeyError: 'bar'

And this is what the same test looks like *with* the patch:

    ======================================================================
    ERROR: test_chain (paralleltest.tests.test_chain.ChainTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/.../django/test/runner.py", line 150, in make_picklable_error
        raise ParallelTestException(msg) from None
    django.test.runner.ParallelTestException: Test exception was chained:
    Test error:
    Traceback (most recent call last):
      File "/.../paralleltest/tests/test_chain.py", line 11, in test_chain
        raise ValueError('foo')
    ValueError: foo

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/.../python3.6/unittest/case.py", line 59, in testPartExecutor
        yield
      File "/.../python3.6/unittest/case.py", line 605, in run
        testMethod()
      File "/.../paralleltest/tests/test_chain.py", line 13, in test_chain
        raise KeyError('bar')
    KeyError: 'bar'

With an example of a non-picklable exception that looks like this:

    class MyException(Exception):

        def __init__(self, foo=None):
            if foo is None:
                raise TypeError('foo cannot be None')

Without the patch, the test run aborts completely with the following
messsage:

    test_non_picklable (paralleltest.tests.test_non_pickleable.MyTest) failed:

        MyException()

    Unfortunately, the exception it raised cannot be pickled, making it impossible
    for the parallel test runner to handle it cleanly.

    Here's the error encountered while trying to pickle the exception:

        TypeError('foo cannot be None',)

    You should re-run this test with the --parallel=1 option to reproduce the
    failure and get a correct traceback.

    Emultiprocessing.pool.RemoteTraceback:
    """
    Traceback (most recent call last):
      File "/.../python3.6/multiprocessing/pool.py", line 119, in worker
        result = (True, func(*args, **kwds))
      File "/.../django/test/runner.py", line 370, in _run_subsuite
        result = runner.run(subsuite)
      File "/.../django/test/runner.py", line 317, in run
        test(result)
      File "/.../python3.6/unittest/suite.py", line 84, in __call__
        return self.run(*args, **kwds)
      File "/.../python3.6/unittest/suite.py", line 122, in run
        test(result)
      File "/.../django/test/testcases.py", line 207, in __call__
        super().__call__(result)
      File "/.../python3.6/unittest/case.py", line 653, in __call__
        return self.run(*args, **kwds)
      File "/.../python3.6/unittest/case.py", line 613, in run
        self._feedErrorsToResult(result, outcome.errors)
      File "/.../python3.6/unittest/case.py", line 543, in _feedErrorsToResult
        result.addError(test, exc_info)
      File "/.../django/test/runner.py", line 256, in addError
        self.check_picklable(test, err)
      File "/.../django/test/runner.py", line 189, in check_picklable
        self._confirm_picklable(err)
      File "/.../django/test/runner.py", line 110, in _confirm_picklable
        pickle.loads(pickle.dumps(obj))
      File "/.../paralleltest/tests/test_non_pickleable.py", line 16, in __init__
        raise TypeError('foo cannot be None')
    TypeError: foo cannot be None
    """

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "manage.py", line 15, in <module>
        execute_from_command_line(sys.argv)
      File "/.../django/core/management/__init__.py", line 373, in execute_from_command_line
        utility.execute()
      File "/.../django/core/management/__init__.py", line 367, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/.../django/core/management/commands/test.py", line 26, in run_from_argv
        super().run_from_argv(argv)
      File "/.../django/core/management/base.py", line 288, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/.../django/core/management/base.py", line 335, in execute
        output = self.handle(*args, **options)
      File "/.../django/core/management/commands/test.py", line 56, in handle
        failures = test_runner.run_tests(test_labels)
      File "/.../django/test/runner.py", line 661, in run_tests
        result = self.run_suite(suite)
      File "/.../django/test/runner.py", line 627, in run_suite
        return runner.run(suite)
      File "/.../python3.6/unittest/runner.py", line 176, in run
        test(result)
      File "/.../python3.6/unittest/suite.py", line 84, in __call__
        return self.run(*args, **kwds)
      File "/.../django/test/runner.py", line 433, in run
        subsuite_index, events = test_results.next(timeout=0.1)
      File "/.../python3.6/multiprocessing/pool.py", line 735, in next
        raise value
    TypeError: foo cannot be None

And this is what the same test looks like *with* the patch.  Moreover,
it is handled seamlessly as a normal test failure instead of aborting
the entire test run:

    ======================================================================
    ERROR: test_non_picklable (paralleltest.tests.test_non_pickleable.MyTest)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/.../django/test/runner.py", line 150, in make_picklable_error
        raise ParallelTestException(msg) from None
    django.test.runner.ParallelTestException: Test exception could not be pickled:
    Test error:
    Traceback (most recent call last):
      File "/.../python3.6/unittest/case.py", line 59, in testPartExecutor
        yield
      File "/.../python3.6/unittest/case.py", line 605, in run
        testMethod()
      File "/.../paralleltest/tests/test_non_pickleable.py", line 23, in test_non_picklable
        raise MyException(foo=1)  # not picklable
    paralleltest.tests.test_non_pickleable.MyException

    Pickle error:
    Traceback (most recent call last):
      File "/.../django/test/runner.py", line 137, in try_pickle
        self._confirm_picklable(err)
      File "/.../django/test/runner.py", line 110, in _confirm_picklable
        pickle.loads(pickle.dumps(obj))
      File "/.../paralleltest/tests/test_non_pickleable.py", line 16, in __init__
        raise TypeError('foo cannot be None')
    TypeError: foo cannot be None